FROM python:3.9.1

RUN apt-get install wget
# psycopg2 for sqlalchemy n
RUN pip install pandas sqlalchemy psycopg2

WORKDIR /app
COPY ingest_data.py ingest_parquet_data.py 

ENTRYPOINT [ "python", "ingest_data.py" ]